### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by NearEarthObject** [bostrot/cloudflare-stream-uploader#1]
Hi,
Thanks before everything providing this idea of plugins.
I have been trying It, but i got the following error upon : node index.js

`SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
`
I am on plesk Linux Centos7.
Any idea how I could solve the problem ?
Thanks 

Jeff

**Comment by bostrot** [comment]
Hi can you please share which version of nodejs and npm you are running? You can get the version with:
`nodejs -v` and `npm -v` just share the output of the two commands.

**Comment by NearEarthObject** [comment]
Hi, the two command return 
npm –v -> 3.10.10
node –v -> v6.16.0

**Comment by NearEarthObject** [comment]
That was completely outdated :) 
installation problem fixed.
So at this point something is going wrong, I put the code here : [http://stream.paddock.racing/](http://stream.paddock.racing/).
zone id, email and api key has been correctly filled.
But something is going wrong. Any idea how to fix it ?
Thanks in advance

**Comment by bostrot** [comment]
I see. That is probably because it requires you to add an authentication flow on your own. 
You could comment that out to test things: `target: '/upload/*?username=' + user + '&token=' + key*/',` (replace line 174 in public/index.html with that)
Second is to make sure that the port which this runs on is not managed by some other program. It may be that apache or nginx (e.g.) block the site `/upload` which is required. While trying you can check it here: http://stream.paddock.racing/upload. 
The port is controlled in `index.js` l. 295 with `httpsServer.listen(80,` instead of 80 try listening on another port. (make sure that the other port you are using is actually accessible and not blocked from the firewall)

I put this code together and kinda forgot about it. Also read the readme. I think I explained a few things there that you should keep in mind.

Edit: Also you may check whether there is an idk /uploads or /video directory in the cloudflare-stream-uploader folder.
